### ISSUE TITLE
Log In

### ISSUE THREAD

**Issue by maxb829** [hmecookd/HomeCooked#1]
Our log in process should have the following pages:

The initiate page, where you can select three options: Log In, Sign Up, or Log In with Facebook.
If you go with either of the first two options, the routing will be the following:
Log In:
The next page will ask you for your email address and password. From there, you are good to go.
Sign Up:
The next page will ask you for your email address and password - the password will have to be entered twice.
From there, you will go to the following page, which will have the Terms and Conditions. After that, registration is complete.

**Comment by valdrinkoshi** [comment]
Login only with FB for v1
