### ISSUE TITLE
APP support: app store, play store, chrome mobile phone, desktop

### ISSUE THREAD

**Issue by dbaq** [hmecookd/HomeCooked#11]
A very important topic has been raised in PR #10.

We were talking about desktop support and chrome version, compares to supporting the app in app stores  (app store (iOS) and play store (Android)

Here is my first message:
 >But about desktop, here you are showing a screenshot for desktop, and on the other PR you're talking about the browser back button.
>The app is designed to be a mobile app, even if right now we are using chrome to develop the app. A lot of code will be specific for mobile purposes (pull-to-refresh, action sheet, etc0 and for cordova(phone camera, phone contacts). This thread on the forum explains my point http://forum.ionicframework.com/t/why-no-desktop/7908/6 (see the answer of mhartington).

>So just to be clear (since @marcandreoli is reading Github notifications):
>the code on this repository should be only for a cordova webview for phones and tablets
>if we want a desktop version app, we will have to make a regular angularjs app or any other technology (we will be able to reuse some services and some code). We will have to use another CSS framework.

@valdrinkoshi replied
> Well no, the code should work in a generic browser (phone or not). I don't remember discussing about limiting the support to phone only (which phone btw? iphone only? android only?). Also, we won't limit the support of hybrid apps only, otherwise we'll be trapped in the circle of publishing a new app (app store, play store).
About mobile specific features, currently we don't have any. Action sheet behaves quite decently also on desktop. I don't think it will harm if we allow users to access homecooked also from their browser on desktop. We should support phone and tablet, and consider "tablet" experience also from desktop.

So for me there is a big question here which needs to be cleared out as soon as possible.

Ionic is for mobile hybrid apps (web technologies embedded in native applications). That means it is not designed for desktop browser.  On their concept page http://ionicframework.com/docs/concepts/structure.html, the first sentence is pretty clear:
> Ionic apps are built with Cordova.

About your comments:

> otherwise we'll be trapped in the circle of publishing a new app (app store, play store).

It is really not an issue + we are building mobile apps, so we will have to go through validation

> About mobile specific features, currently we don't have any. 

We will have a lot very soon. Camera/Gallery for pictures for instance. 

For the future:
* push notifications
* native facebook connect 
* contact list access
* phone number access
* being able to start a call
* being able to send SMS

You won't be able to do anything like that on browsers.

> Action sheet behaves quite decently also on desktop.

You need to have a specific UX, you can't just have action sheet and pull to refresh on desktop. That won't work in terms of UX

> consider "tablet" experience also from desktop

No, you have to consider tablet, a simple special case for phone, with a wider screen.

So to be clear, ionic is for hybrid apps if you guys want a "browser apps", which means not a native app but an app that you access in your browser from a URL. Ionic is not the appropriate technology. Ionic is for mobile apps for iOS, Android and other platforms (Windows phone etc).

IMHO, native apps is definitely the way to go, you can benefit of native features like push notifications, access to camera/gallery, provide native experience, etc. Also if you are using a browser, the user will have to log in every time because you won't use a shared localstorage to store the user token (security issue here, on a cordova, each app has its own localstorage). 

So I am for the support of Android and iOS for the alpha, tablets can come for the v1 (very easy to maintain). And do not let the users use browsers to access the app. We are doing a native app not a web app.

**Comment by dbaq** [comment]
Please read the updated issue, I hit saved by mistake.

**Comment by valdrinkoshi** [comment]
Ionic brings a lot of stuff for supporting hybrid apps, but works quite well on browser too (mobile and desktop). All ionic UI widgets are designed for the mobile, but they still behave good on desktop as well, and on the web browsers of the devices. I wouldn't lock ourselves in hybrid/native apps, I believe this might slow us significantly. We already discussed about the support of which platforms, and for v1 we want to have 1 codebase that works on the web browser of as many platforms as possible.
We need to get location of the user and upload images from their device. Both are possible on a webapp (see http://www.html5rocks.com/en/tutorials/getusermedia/intro/)

@marcandreoli give your input as well. Do we want to support only iphone for v1? in that case we can go hybrid/native and that's it. This is a shift from the initial plan, parts of the app have to be revisited (e.g. facebook integration)

**Comment by valdrinkoshi** [comment]
We can go hybrid/native after v1, when we have enough metrics on our users, which devices are mostly used, etc..

**Comment by valdrinkoshi** [comment]
For notifications, we'll rely on sms for v1

**Comment by dbaq** [comment]
why iphone only? the support for android does not require more work for the v1.

**Comment by valdrinkoshi** [comment]
It would mean another store to follow, wait for approval, etc.
We should provide native application for v2. Web support will allow us broader audience and freedom of updates.
At least, that's my understanding so far. We integrated facebook with their web SDK for this reason. If this is no more true, we have to adjust soon. @marcandreoli please chip in.
@jonbwhite FYI

**Comment by dbaq** [comment]
IMHO, going native after the v1 is not the right way to do it. People are expecting native apps, they won't use their phones, go to the browser and enter the app URL. That's for sure. They just want to tap an icon.

The effort of going native is not that big as you think. Ionic is developing something to facilitate and bypass the struggle of app store: http://docs.ionic.io/v1.0/docs/deploy-install

The android store validation is about 12 hours. The iOS store validation is between 7 days to 3 weeks. So by experience, android is way easier.

**Comment by valdrinkoshi** [comment]
That's true for the buyers, but maybe for chefs having a desktop/tablet version might be more useful.
There is a way to have your website as an icon of iphone too (google maps used to do that for a while until they didn't implement the google maps app for ios).
The key thing we should understand here is: should we support desktop or not?
If no, let's just go hybrid/native. If we want to support desktop, let's go with web application

**Comment by marcandreoli** [comment]
Yes, mobile is definately the priority over desktop. Since the UX would vary on a desktop, let's focus on mobile, and put browser availability on hold. Localization for tablets is a low hanging fruit, which we can pursue shortly after the Alpha.

**Comment by marcandreoli** [comment]
I am still very much in favor of 1 codebase that works accross the web browsers of as many platforms as possible.

**Comment by valdrinkoshi** [comment]
Alright then, v1 will be only on iphone/android native apps.
@marcandreoli, we'll see where we are after v1, and implement desktop version reusing services mainly, rewriting the views.

**Comment by marcandreoli** [comment]
Keep in mind that many of our vendors will be "average Joe's": guys who are more likely to use Android devices. 
For the Alpha, I was hoping to make the app available through the Play store on Android (since it takes 24hours to get going), and Ionic for iOS (since it takes 3 weeks to possibly be accepted on the Apple store). @valdrinkoshi @dbaq Is this feasible?

**Comment by dbaq** [comment]
I think we should go fully mobile on both platforms. Dont worry about the validation time of iOS. Let's focus on the dev and iterate quickly on the most important features.and everything is going to be fine even if we have to wait 2 more weeks to have the iOS version out.

**Comment by marcandreoli** [comment]
Ok thanks.
@dbaq I assume that once an app has been accepted on the Apple store, code changes (updates and enhancements) do not take 2 weeks to get approved, but are pushed automatically. yes?

**Comment by dbaq** [comment]
Nope, Around 10 days. But ionic is working on a service (link in my comment above). To update remotely so we can skip the validation process.

Complains to apple for that or Arthur. It is the same thing for the all apps.

**Comment by valdrinkoshi** [comment]
I agree, let's go with native apps only. I will enable the developer account for apple already and include @dbaq as dev there

**Comment by dbaq** [comment]
Closing this issue.
