### ISSUE TITLE
Sign in/Sign up should not be required until the check out

### ISSUE THREAD

**Issue by dbaq** [hmecookd/HomeCooked#16]
Hey guys,

I would like to propose a change in the flow of the application. I have analyzed other food apps (grubhub, eat24, munchery), none of them require a sign up before using the app.

![Grubhub](https://lh3.googleusercontent.com/UcUA8OcmHbfJqzHs2Kq1I43vbZ6tjn1sIfdiutyJZBb8)
![Eat24](https://lh3.googleusercontent.com/mM8Nf2KiHW8UWKVWUTQ2sYnVbJsJrr8BHCGtsOpghWBa)
![Munchery](https://lh3.googleusercontent.com/HXNtLR6QYPBm0FU809KMFI2k77OhnlyUSbbKPbas6GwP)

I am pretty confident to say that other food apps are working the same way. You can signin/signup whenever you want, and if you don't, you have to do it at the end of the checkout, or when you want to switch the "chef portal".

If those big applications are doing it this way, it is because that's probably the best way to go. It is less friction for the end user, he downloads the app and start placing his order right away.

What's the impact for us? if we do it now, we are talking about a few commits on the front end side (that I can do). On the backend side, we need to make the API to browse the dishes/chefs and place an order public (I guess it is easy to do also).

So if you guys can give me your thoughts on it, that would great! thanks @marcandreoli @valdrinkoshi

**Comment by marcandreoli** [comment]
@dbaq :
We make people sign up before using the app for two reasons:

1-because legally, it looks way better if we are an invitation-only marketplace, rather than a public marketplace --> However, I am reaching out to Rob right now (our lawyer dude) to confirm or refute that this is also valid for buyers.
2-because we want to prevent scenarios where users sign on to a marketplace with zero vendors. Making users register before usage means we can accept those in the right zip codes. I am not sure this is super compelling though.

@dbaq I will get back to you after talking to Rob. @valdrinkoshi @jonbwhite thoughts? 
What could be some negative side effects of letting buyers navigate the marketplace before creating an account?

**Comment by dbaq** [comment]
> 1-because legally, it looks way better if we are an invitation-only marketplace, rather than a public marketplace --> However, I am reaching out to Rob right now (our lawyer dude) to confirm or refute that this is also valid for buyers.
2-because we want to prevent scenarios where users sign on to a marketplace with zero vendors. Making users register before usage means we can accept those in the right zip codes. I am not sure this is super compelling though.

We can ask for an invitation code or check if their location is in the "location whitelist" 

![zip code checking](https://lh3.googleusercontent.com/OyTNdAYWMPFFdQzFqE5AkpFV2Cd2xe4iuf-wD32MyJCu)

![zip code invalid](https://lh3.googleusercontent.com/KdaK7KrJc4KpPN_a2ExbiHAJkiaxnUDzI3V1rUBAv1g3=)

that easy

**Comment by marcandreoli** [comment]
@dbaq 
Wow I love it. Need to confirm the legal aspect of it and will get back to you asap

**Comment by dbaq** [comment]
And also thanks to something like that, you will have a "prefiltered search" for this screen, since you can reuse the zip code that the guy just entered:

![screen shot 2015-06-08 at 5 55 50 pm](https://cloud.githubusercontent.com/assets/1867703/8048546/aa3d8fdc-0e07-11e5-9cae-90242b58d3c8.png)

I can have this feature done by wednesday night.

**Comment by marcandreoli** [comment]
Buyers should be able to look outside of their current zip code as well though, some of them will want to pick-up on their way home from work, for example.

Eventually, I would like to eliminate this page, and instead go directly to the real-time Yelp-like map that is populated based on the users location. With a 'list view' option in a corner.

Are we reducing development work with the current address prompt? If so, I am fine to do it this way for the Alpha.

**Comment by marcandreoli** [comment]
If not, then I can update the mock-ups with a new 'home page', i.e. the real-time Yelp-like map.

**Comment by dbaq** [comment]
Well two things here:

- zip code restrictions because it is an alpha, so before accessing the app we ask for the zip code, if it is not available we display a message, and if you look at the screenshot above their is a link "change your zipcode", so the users are not stuck.

- and then about search, when I say it is prefiltered, that means you can change it to whatever you want on the search page.

we are going off topic now, I am almost done for the optional Signup flow. I will probably open a PR tomorrow so we can discuss it.

I have plenty of code we can reuse for maps, just update the mockups and let us via slack or another issue when it is done so we can discuss and implement what you want. I will be pretty fast to do I believe.

**Comment by valdrinkoshi** [comment]
I'm fine with the proposal, as far as legally we are good. I think then we should hide the side menu if the user didn't sign in, right?
We need to hear also from BE side ( @jonbwhite ) if having these apis public is fine or there are some implications.

**Comment by valdrinkoshi** [comment]
About the zip codes restrictions, that should be restricted only to where the chefs are, not to where the user is.
If user searches on an area that we don't support, we should allow him to ask homecooked to support that area (the "get notified" thing in the previous picture of @dbaq )

**Comment by dbaq** [comment]
I created a PR for the non blocking signup https://github.com/hmecookd/HomeCooked/pull/17. Mainly to experiment.

About hiding the left menu, I kinda agree (like grubhub) because it is simple, you place an order or you login to access details of your account. But you might want to be able to access Help or Terms & Privacy pages, and it could increase the conversion to see the "become a chef" link.

I guess in the alpha, we could simply hide the menu button. And the links for terms and privacy could be in sign up modal or on the search page at the bottom.

**Comment by dbaq** [comment]
Anyway @valdrinkoshi if you can spend a few minutes to review/experiment it, that would be awesome!

**Comment by valdrinkoshi** [comment]
Done. I think is fine to hide the menu and have the sign in button only for v1. In the sign in popup we can put the link to terms & conditions right under the login button ;)

**Comment by valdrinkoshi** [comment]
Closing the issue as the PR has been merged. Thanks @dbaq!
